`ifndef HART_EXPT_IF_SVH
`define HART_EXPT_IF_SVH

typedef enum logic [1:0] {
    HART_EXPT_TYPE_EXCEPTION = 2'd0,
    HART_EXPT_TYPE_MRET = 2'd1,
    HART_EXPT_TYPE_SRET = 2'd2
} hart_expt_type_t;

typedef enum logic [4:0] {
    HART_EXPT_CAUSE_INST_ADDR_MISALIGNED = 5'd0,
    HART_EXPT_CAUSE_INST_ACCESS_FAULT = 5'd1,
    HART_EXPT_CAUSE_ILLEGAL_INST = 5'd2,
    HART_EXPT_CAUSE_BREAKPOINT = 5'd3,
    HART_EXPT_CAUSE_LOAD_ADDR_MISALIGNED = 5'd4,
    HART_EXPT_CAUSE_LOAD_ACCESS_FAULT = 5'd5,
    HART_EXPT_CAUSE_STORE_AMO_ADDR_MISALIGNED = 5'd6,
    HART_EXPT_CAUSE_STORE_AMO_ACCESS_FAULT = 5'd7,
    HART_EXPT_CAUSE_ECALL = 5'd8,
    HART_EXPT_CAUSE_INST_PAGE_FAULT = 5'd12,
    HART_EXPT_CAUSE_LOAD_PAGE_FAULT = 5'd13,
    HART_EXPT_CAUSE_STORE_AMO_PAGE_FAULT = 5'd15,
    HART_EXPT_CAUSE_DOUBLE_TRAP = 5'd16,
    HART_EXPT_CAUSE_SW_CHECK = 5'd18,
    HART_EXPT_CAUSE_HW_ERROR = 5'd19
} hart_expt_cause_t;

`endif
