`ifndef HART_SVH
`define HART_SVH

`define MMU_ITLB_SIZE 64
`define MMU_DTLB_SIZE 32

`define BPU_COND_BHT_SIZE 64
`define BPU_JALR_BTB_SIZE 16
`define BPU_JALR_BTB_WAY_NUM 4
`define BPU_RAS_SIZE      16

`define FCH_TRANS_ID  16'h0000
`define LDST_TRANS_ID 16'h0001

`define HART_IFU_CTRLQ_DEPTH    8
`define HART_IFU_FCH_OST_DEPTH  8

`define HART_HBI_STG_FIFO_DEPTH 4
`define HART_HBI_I_OST_DEPTH    8
`define HART_HBI_D_OST_DEPTH    4

`define HART_LSU_STG_FIFO_DEPTH 2
`define HART_LSU_OST_DEPTH      2

`define HART_MMU_I_STG_FIFO_DEPTH 8
`define HART_MMU_D_STG_FIFO_DEPTH 4
`define HART_MMU_OST_DEPTH       8

`define HART_L1I_STG_FIFO_DEPTH 8
`define HART_L1D_STG_FIFO_DEPTH 4
`define HART_L1_OST_DEPTH       8
`define HART_L1D_BTI_MUX_STG_FIFO_DEPTH 4
`define HART_L1D_BTI_MUX_OST_DEPTH 8

`define L1_LINE_SIZE 64
`define L1I_SIZE     16384
`define L1I_WAY_NUM  2
`define L1D_SIZE     16384
`define L1D_WAY_NUM  2

`endif
