// Generated by tools/pcmgen.py from desc/pcm.json.

`include "dbg/pcm_perf.svh"

module pcm_perf #(
    parameter int COUNTER_NUM = `RVB_PCM_COUNTER_NUM
)(
    output logic [COUNTER_NUM-1:0] inc_en,
    perf_soc_if_t.slv perf_u_soc_slv,
    perf_axi_demux_if_t.slv perf_u_soc_u_mm_axi_demux_slv,
    perf_rv32g_if_t.slv perf_u_soc_u_rv32g_cpu_slv,
    perf_axi_demux_if_t.slv perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv,
    perf_axi_demux_if_t.slv perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv,
    perf_l2_if_t.slv perf_u_soc_u_rv32g_cpu_u_l2_slv,
    perf_ifu_if_t.slv perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv,
    perf_bpu_if_t.slv perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv,
    perf_mmu_if_t.slv perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv,
    perf_l1_if_t.slv perf_u_soc_u_rv32g_cpu_u_hart_u_l1i_slv,
    perf_l1_if_t.slv perf_u_soc_u_rv32g_cpu_u_hart_u_l1d_slv,
    perf_exu_if_t.slv perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv,
    perf_lsu_if_t.slv perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv
);
    always_comb begin
        inc_en = '0;
        inc_en[0] = perf_u_soc_slv.pkt.cycle; // u_soc.cycle
        inc_en[1] = perf_u_soc_slv.pkt.soc_mm_aw_bp; // u_soc.soc_mm_aw_bp
        inc_en[2] = perf_u_soc_slv.pkt.soc_mm_w_bp; // u_soc.soc_mm_w_bp
        inc_en[3] = perf_u_soc_slv.pkt.soc_mm_ar_bp; // u_soc.soc_mm_ar_bp
        inc_en[4] = perf_u_soc_slv.pkt.soc_mm_b_bp; // u_soc.soc_mm_b_bp
        inc_en[5] = perf_u_soc_slv.pkt.soc_mm_r_bp; // u_soc.soc_mm_r_bp
        inc_en[6] = perf_u_soc_slv.pkt.soc_ddr_aw_bp; // u_soc.soc_ddr_aw_bp
        inc_en[7] = perf_u_soc_slv.pkt.soc_ddr_w_bp; // u_soc.soc_ddr_w_bp
        inc_en[8] = perf_u_soc_slv.pkt.soc_ddr_ar_bp; // u_soc.soc_ddr_ar_bp
        inc_en[9] = perf_u_soc_slv.pkt.soc_ddr_b_bp; // u_soc.soc_ddr_b_bp
        inc_en[10] = perf_u_soc_slv.pkt.soc_ddr_r_bp; // u_soc.soc_ddr_r_bp
        inc_en[11] = perf_u_soc_slv.pkt.soc_flash_aw_bp; // u_soc.soc_flash_aw_bp
        inc_en[12] = perf_u_soc_slv.pkt.soc_flash_w_bp; // u_soc.soc_flash_w_bp
        inc_en[13] = perf_u_soc_slv.pkt.soc_flash_ar_bp; // u_soc.soc_flash_ar_bp
        inc_en[14] = perf_u_soc_slv.pkt.soc_flash_b_bp; // u_soc.soc_flash_b_bp
        inc_en[15] = perf_u_soc_slv.pkt.soc_flash_r_bp; // u_soc.soc_flash_r_bp
        inc_en[16] = perf_u_soc_slv.pkt.peri_apb_bp; // u_soc.peri_apb_bp
        inc_en[17] = perf_u_soc_u_mm_axi_demux_slv.pkt.rd_ost_full; // u_soc.u_mm_axi_demux.rd_ost_full
        inc_en[18] = perf_u_soc_u_mm_axi_demux_slv.pkt.wr_ost_full; // u_soc.u_mm_axi_demux.wr_ost_full
        inc_en[19] = perf_u_soc_u_mm_axi_demux_slv.pkt.ar_stg_full; // u_soc.u_mm_axi_demux.ar_stg_full
        inc_en[20] = perf_u_soc_u_mm_axi_demux_slv.pkt.aw_stg_full; // u_soc.u_mm_axi_demux.aw_stg_full
        inc_en[21] = perf_u_soc_u_mm_axi_demux_slv.pkt.w_stg_full; // u_soc.u_mm_axi_demux.w_stg_full
        inc_en[22] = perf_u_soc_u_mm_axi_demux_slv.pkt.ar_issue_bp; // u_soc.u_mm_axi_demux.ar_issue_bp
        inc_en[23] = perf_u_soc_u_mm_axi_demux_slv.pkt.aw_issue_bp; // u_soc.u_mm_axi_demux.aw_issue_bp
        inc_en[24] = perf_u_soc_u_mm_axi_demux_slv.pkt.w_issue_bp; // u_soc.u_mm_axi_demux.w_issue_bp
        inc_en[25] = perf_u_soc_u_mm_axi_demux_slv.pkt.r_rsp_bp; // u_soc.u_mm_axi_demux.r_rsp_bp
        inc_en[26] = perf_u_soc_u_mm_axi_demux_slv.pkt.b_rsp_bp; // u_soc.u_mm_axi_demux.b_rsp_bp
        inc_en[27] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_i_aw_bp; // u_soc.u_rv32g_cpu.hart_i_aw_bp
        inc_en[28] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_i_w_bp; // u_soc.u_rv32g_cpu.hart_i_w_bp
        inc_en[29] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_i_ar_bp; // u_soc.u_rv32g_cpu.hart_i_ar_bp
        inc_en[30] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_i_b_bp; // u_soc.u_rv32g_cpu.hart_i_b_bp
        inc_en[31] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_i_r_bp; // u_soc.u_rv32g_cpu.hart_i_r_bp
        inc_en[32] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_d_aw_bp; // u_soc.u_rv32g_cpu.hart_d_aw_bp
        inc_en[33] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_d_w_bp; // u_soc.u_rv32g_cpu.hart_d_w_bp
        inc_en[34] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_d_ar_bp; // u_soc.u_rv32g_cpu.hart_d_ar_bp
        inc_en[35] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_d_b_bp; // u_soc.u_rv32g_cpu.hart_d_b_bp
        inc_en[36] = perf_u_soc_u_rv32g_cpu_slv.pkt.hart_d_r_bp; // u_soc.u_rv32g_cpu.hart_d_r_bp
        inc_en[37] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_i_aw_bp; // u_soc.u_rv32g_cpu.cbi_i_aw_bp
        inc_en[38] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_i_w_bp; // u_soc.u_rv32g_cpu.cbi_i_w_bp
        inc_en[39] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_i_ar_bp; // u_soc.u_rv32g_cpu.cbi_i_ar_bp
        inc_en[40] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_i_b_bp; // u_soc.u_rv32g_cpu.cbi_i_b_bp
        inc_en[41] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_i_r_bp; // u_soc.u_rv32g_cpu.cbi_i_r_bp
        inc_en[42] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_d_aw_bp; // u_soc.u_rv32g_cpu.cbi_d_aw_bp
        inc_en[43] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_d_w_bp; // u_soc.u_rv32g_cpu.cbi_d_w_bp
        inc_en[44] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_d_ar_bp; // u_soc.u_rv32g_cpu.cbi_d_ar_bp
        inc_en[45] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_d_b_bp; // u_soc.u_rv32g_cpu.cbi_d_b_bp
        inc_en[46] = perf_u_soc_u_rv32g_cpu_slv.pkt.cbi_d_r_bp; // u_soc.u_rv32g_cpu.cbi_d_r_bp
        inc_en[47] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_i_aw_bp; // u_soc.u_rv32g_cpu.l2_i_aw_bp
        inc_en[48] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_i_w_bp; // u_soc.u_rv32g_cpu.l2_i_w_bp
        inc_en[49] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_i_ar_bp; // u_soc.u_rv32g_cpu.l2_i_ar_bp
        inc_en[50] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_i_b_bp; // u_soc.u_rv32g_cpu.l2_i_b_bp
        inc_en[51] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_i_r_bp; // u_soc.u_rv32g_cpu.l2_i_r_bp
        inc_en[52] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_d_aw_bp; // u_soc.u_rv32g_cpu.l2_d_aw_bp
        inc_en[53] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_d_w_bp; // u_soc.u_rv32g_cpu.l2_d_w_bp
        inc_en[54] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_d_ar_bp; // u_soc.u_rv32g_cpu.l2_d_ar_bp
        inc_en[55] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_d_b_bp; // u_soc.u_rv32g_cpu.l2_d_b_bp
        inc_en[56] = perf_u_soc_u_rv32g_cpu_slv.pkt.l2_d_r_bp; // u_soc.u_rv32g_cpu.l2_d_r_bp
        inc_en[57] = perf_u_soc_u_rv32g_cpu_slv.pkt.cfg_apb_bp; // u_soc.u_rv32g_cpu.cfg_apb_bp
        inc_en[58] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.rd_ost_full; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.rd_ost_full
        inc_en[59] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.wr_ost_full; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.wr_ost_full
        inc_en[60] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.ar_stg_full; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.ar_stg_full
        inc_en[61] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.aw_stg_full; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.aw_stg_full
        inc_en[62] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.w_stg_full; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.w_stg_full
        inc_en[63] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.ar_issue_bp; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.ar_issue_bp
        inc_en[64] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.aw_issue_bp; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.aw_issue_bp
        inc_en[65] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.w_issue_bp; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.w_issue_bp
        inc_en[66] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.r_rsp_bp; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.r_rsp_bp
        inc_en[67] = perf_u_soc_u_rv32g_cpu_u_cbi_u_i_axi_demux_slv.pkt.b_rsp_bp; // u_soc.u_rv32g_cpu.u_cbi.u_i_axi_demux.b_rsp_bp
        inc_en[68] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.rd_ost_full; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.rd_ost_full
        inc_en[69] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.wr_ost_full; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.wr_ost_full
        inc_en[70] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.ar_stg_full; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.ar_stg_full
        inc_en[71] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.aw_stg_full; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.aw_stg_full
        inc_en[72] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.w_stg_full; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.w_stg_full
        inc_en[73] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.ar_issue_bp; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.ar_issue_bp
        inc_en[74] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.aw_issue_bp; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.aw_issue_bp
        inc_en[75] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.w_issue_bp; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.w_issue_bp
        inc_en[76] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.r_rsp_bp; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.r_rsp_bp
        inc_en[77] = perf_u_soc_u_rv32g_cpu_u_cbi_u_d_axi_demux_slv.pkt.b_rsp_bp; // u_soc.u_rv32g_cpu.u_cbi.u_d_axi_demux.b_rsp_bp
        inc_en[78] = perf_u_soc_u_rv32g_cpu_u_l2_slv.pkt.hit; // u_soc.u_rv32g_cpu.u_l2.hit
        inc_en[79] = perf_u_soc_u_rv32g_cpu_u_l2_slv.pkt.miss; // u_soc.u_rv32g_cpu.u_l2.miss
        inc_en[80] = perf_u_soc_u_rv32g_cpu_u_l2_slv.pkt.bypass; // u_soc.u_rv32g_cpu.u_l2.bypass
        inc_en[81] = perf_u_soc_u_rv32g_cpu_u_l2_slv.pkt.writeback; // u_soc.u_rv32g_cpu.u_l2.writeback
        inc_en[82] = perf_u_soc_u_rv32g_cpu_u_l2_slv.pkt.busy; // u_soc.u_rv32g_cpu.u_l2.busy
        inc_en[83] = perf_u_soc_u_rv32g_cpu_u_l2_slv.pkt.i_busy; // u_soc.u_rv32g_cpu.u_l2.i_busy
        inc_en[84] = perf_u_soc_u_rv32g_cpu_u_l2_slv.pkt.d_busy; // u_soc.u_rv32g_cpu.u_l2.d_busy
        inc_en[85] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.fch_rsp_inst; // u_soc.u_rv32g_cpu.u_hart.u_ifu.fch_rsp_inst
        inc_en[86] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.fch_ost_full; // u_soc.u_rv32g_cpu.u_hart.u_ifu.fch_ost_full
        inc_en[87] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.fch_rspq_bp; // u_soc.u_rv32g_cpu.u_hart.u_ifu.fch_rspq_bp
        inc_en[88] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.ctrlq_bp; // u_soc.u_rv32g_cpu.u_hart.u_ifu.ctrlq_bp
        inc_en[89] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.ex_req_bp; // u_soc.u_rv32g_cpu.u_hart.u_ifu.ex_req_bp
        inc_en[90] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.fch_req_bp; // u_soc.u_rv32g_cpu.u_hart.u_ifu.fch_req_bp
        inc_en[91] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.pred_wait; // u_soc.u_rv32g_cpu.u_hart.u_ifu.pred_wait
        inc_en[92] = perf_u_soc_u_rv32g_cpu_u_hart_u_ifu_slv.pkt.issue_hold; // u_soc.u_rv32g_cpu.u_hart.u_ifu.issue_hold
        inc_en[93] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.branch; // u_soc.u_rv32g_cpu.u_hart.u_bpu.branch
        inc_en[94] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.pred_true; // u_soc.u_rv32g_cpu.u_hart.u_bpu.pred_true
        inc_en[95] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.pred_false; // u_soc.u_rv32g_cpu.u_hart.u_bpu.pred_false
        inc_en[96] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.cond_branch; // u_soc.u_rv32g_cpu.u_hart.u_bpu.cond_branch
        inc_en[97] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.cond_branch_pred_true; // u_soc.u_rv32g_cpu.u_hart.u_bpu.cond_branch_pred_true
        inc_en[98] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.jal; // u_soc.u_rv32g_cpu.u_hart.u_bpu.jal
        inc_en[99] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.jal_pred_true; // u_soc.u_rv32g_cpu.u_hart.u_bpu.jal_pred_true
        inc_en[100] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.jalr; // u_soc.u_rv32g_cpu.u_hart.u_bpu.jalr
        inc_en[101] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.jalr_pred_true; // u_soc.u_rv32g_cpu.u_hart.u_bpu.jalr_pred_true
        inc_en[102] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.cond_bht_hit; // u_soc.u_rv32g_cpu.u_hart.u_bpu.cond_bht_hit
        inc_en[103] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.jalr_ras_hit; // u_soc.u_rv32g_cpu.u_hart.u_bpu.jalr_ras_hit
        inc_en[104] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.jalr_btb_hit; // u_soc.u_rv32g_cpu.u_hart.u_bpu.jalr_btb_hit
        inc_en[105] = perf_u_soc_u_rv32g_cpu_u_hart_u_bpu_slv.pkt.jalr_btb_miss; // u_soc.u_rv32g_cpu.u_hart.u_bpu.jalr_btb_miss
        inc_en[106] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.itlb_hit; // u_soc.u_rv32g_cpu.u_hart.u_mmu.itlb_hit
        inc_en[107] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.itlb_miss; // u_soc.u_rv32g_cpu.u_hart.u_mmu.itlb_miss
        inc_en[108] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.dtlb_hit; // u_soc.u_rv32g_cpu.u_hart.u_mmu.dtlb_hit
        inc_en[109] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.dtlb_miss; // u_soc.u_rv32g_cpu.u_hart.u_mmu.dtlb_miss
        inc_en[110] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.i_stg_full; // u_soc.u_rv32g_cpu.u_hart.u_mmu.i_stg_full
        inc_en[111] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.d_stg_full; // u_soc.u_rv32g_cpu.u_hart.u_mmu.d_stg_full
        inc_en[112] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.i_ost_full; // u_soc.u_rv32g_cpu.u_hart.u_mmu.i_ost_full
        inc_en[113] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.d_ost_full; // u_soc.u_rv32g_cpu.u_hart.u_mmu.d_ost_full
        inc_en[114] = perf_u_soc_u_rv32g_cpu_u_hart_u_mmu_slv.pkt.ptw_busy; // u_soc.u_rv32g_cpu.u_hart.u_mmu.ptw_busy
        inc_en[115] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1i_slv.pkt.hit; // u_soc.u_rv32g_cpu.u_hart.u_l1i.hit
        inc_en[116] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1i_slv.pkt.miss; // u_soc.u_rv32g_cpu.u_hart.u_l1i.miss
        inc_en[117] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1i_slv.pkt.bypass; // u_soc.u_rv32g_cpu.u_hart.u_l1i.bypass
        inc_en[118] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1i_slv.pkt.writeback; // u_soc.u_rv32g_cpu.u_hart.u_l1i.writeback
        inc_en[119] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1i_slv.pkt.busy; // u_soc.u_rv32g_cpu.u_hart.u_l1i.busy
        inc_en[120] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1d_slv.pkt.hit; // u_soc.u_rv32g_cpu.u_hart.u_l1d.hit
        inc_en[121] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1d_slv.pkt.miss; // u_soc.u_rv32g_cpu.u_hart.u_l1d.miss
        inc_en[122] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1d_slv.pkt.bypass; // u_soc.u_rv32g_cpu.u_hart.u_l1d.bypass
        inc_en[123] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1d_slv.pkt.writeback; // u_soc.u_rv32g_cpu.u_hart.u_l1d.writeback
        inc_en[124] = perf_u_soc_u_rv32g_cpu_u_hart_u_l1d_slv.pkt.busy; // u_soc.u_rv32g_cpu.u_hart.u_l1d.busy
        inc_en[125] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.ex_req; // u_soc.u_rv32g_cpu.u_hart.u_exu.ex_req
        inc_en[126] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.alu_inst; // u_soc.u_rv32g_cpu.u_hart.u_exu.alu_inst
        inc_en[127] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.branch_inst; // u_soc.u_rv32g_cpu.u_hart.u_exu.branch_inst
        inc_en[128] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.ldst_inst; // u_soc.u_rv32g_cpu.u_hart.u_exu.ldst_inst
        inc_en[129] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.misc_inst; // u_soc.u_rv32g_cpu.u_hart.u_exu.misc_inst
        inc_en[130] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.sys_inst; // u_soc.u_rv32g_cpu.u_hart.u_exu.sys_inst
        inc_en[131] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.wfi_stall; // u_soc.u_rv32g_cpu.u_hart.u_exu.wfi_stall
        inc_en[132] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.flush_drop; // u_soc.u_rv32g_cpu.u_hart.u_exu.flush_drop
        inc_en[133] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.alu_busy; // u_soc.u_rv32g_cpu.u_hart.u_exu.alu_busy
        inc_en[134] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.branch_busy; // u_soc.u_rv32g_cpu.u_hart.u_exu.branch_busy
        inc_en[135] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.ldst_busy; // u_soc.u_rv32g_cpu.u_hart.u_exu.ldst_busy
        inc_en[136] = perf_u_soc_u_rv32g_cpu_u_hart_u_exu_slv.pkt.sys_busy; // u_soc.u_rv32g_cpu.u_hart.u_exu.sys_busy
        inc_en[137] = perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv.pkt.exu_req; // u_soc.u_rv32g_cpu.u_hart.u_lsu.exu_req
        inc_en[138] = perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv.pkt.direct_req_bp; // u_soc.u_rv32g_cpu.u_hart.u_lsu.direct_req_bp
        inc_en[139] = perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv.pkt.direct_rsp_wait; // u_soc.u_rv32g_cpu.u_hart.u_lsu.direct_rsp_wait
        inc_en[140] = perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv.pkt.split_req; // u_soc.u_rv32g_cpu.u_hart.u_lsu.split_req
        inc_en[141] = perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv.pkt.split_req_bp; // u_soc.u_rv32g_cpu.u_hart.u_lsu.split_req_bp
        inc_en[142] = perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv.pkt.split_rsp_wait; // u_soc.u_rv32g_cpu.u_hart.u_lsu.split_rsp_wait
        inc_en[143] = perf_u_soc_u_rv32g_cpu_u_hart_u_lsu_slv.pkt.exu_rsp_bp; // u_soc.u_rv32g_cpu.u_hart.u_lsu.exu_rsp_bp
    end
endmodule
