#!/usr/bin/env python3

import argparse
import json
import os
import sys


def fail(msg):
    print(f"asic_config.py: {msg}", file=sys.stderr)
    sys.exit(1)


def tcl_quote(val):
    text = str(val)
    return "{" + text.replace("\\", "\\\\").replace("}", "\\}") + "}"


def tcl_list(vals):
    return "[list " + " ".join(tcl_quote(v) for v in vals) + "]"


def get_obj(obj, key, default=None):
    val = obj.get(key, default)
    if val is None:
        fail(f"missing required key: {key}")
    return val


def norm_path(path):
    return os.path.normpath(os.path.expandvars(os.path.expanduser(path)))


def pdk_path(root, path):
    path = os.path.expandvars(os.path.expanduser(path))
    if os.path.isabs(path):
        return os.path.normpath(path)
    return os.path.normpath(os.path.join(root, path))


def emit(name, val):
    print(f"set {name} {tcl_quote(val)}")


def emit_list(name, vals):
    print(f"set {name} {tcl_list(vals)}")


def load_json(path):
    with open(path, "r", encoding="utf-8") as fp:
        return json.load(fp)


def resolve_path(base_dir, path):
    path = os.path.expandvars(os.path.expanduser(path))
    if os.path.isabs(path):
        return os.path.normpath(path)
    return os.path.normpath(os.path.join(base_dir, path))


def rel_to_root(root, path):
    path = os.path.normpath(path)
    if os.path.isabs(path):
        try:
            return os.path.relpath(path, root)
        except ValueError:
            return path
    return path


def collect_rtl_files(root, conf):
    rtl = conf.get("rtl", {})
    entries = []
    entries.extend(rtl.get("file_groups", []))
    entries.extend(rtl.get("files", []))
    excludes = {
        resolve_path(root, path)
        for path in rtl.get("exclude", [])
    }

    files = []
    seen = set()
    for entry in entries:
        path = resolve_path(root, entry)
        if os.path.isdir(path):
            for cur_root, dirs, names in os.walk(path):
                dirs.sort()
                for name in sorted(names):
                    file_path = os.path.join(cur_root, name)
                    if name.endswith(".sv") and file_path not in excludes:
                        files.append(file_path)
        elif os.path.isfile(path):
            if path not in excludes:
                files.append(path)
        else:
            fail(f"RTL file/group not found: {entry}")

    out = []
    for path in files:
        rel = rel_to_root(root, path)
        if rel in seen:
            continue
        seen.add(rel)
        out.append(rel)
    if not out:
        fail("rtl.file_groups/files produced an empty RTL list")
    return out


def write_rtl_file(path, root, conf_path, conf):
    files = collect_rtl_files(root, conf)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fp:
        fp.write("# Generated by tools/asic_config.py.\n")
        fp.write(f"# Config: {os.path.abspath(conf_path)}\n\n")
        for file_name in files:
            fp.write(f"{file_name}\n")


def resolve_pdk_conf(conf_path, conf):
    pdk_ref = get_obj(conf, "pdk")
    if isinstance(pdk_ref, str):
        pdk_path_val = resolve_path(os.path.dirname(conf_path), pdk_ref)
        pdk_conf = load_json(pdk_path_val)
        return pdk_path_val, pdk_conf
    if isinstance(pdk_ref, dict):
        return conf_path, pdk_ref
    fail("pdk must be a path string or object")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("conf_json")
    parser.add_argument("--root", default=os.getcwd())
    parser.add_argument("--rtl-file")
    args = parser.parse_args()

    root = os.path.abspath(args.root)
    conf_path = os.path.abspath(args.conf_json)
    conf = load_json(conf_path)
    pdk_conf_path, pdk_conf = resolve_pdk_conf(conf_path, conf)

    if args.rtl_file:
        write_rtl_file(os.path.abspath(args.rtl_file), root, conf_path, conf)

    pdk = get_obj(pdk_conf, "pdk")
    pdk_root = norm_path(get_obj(pdk, "root"))
    libs = get_obj(pdk_conf, "libraries")
    clock = get_obj(conf, "clock")
    constraints = conf.get("constraints", {})
    driving = constraints.get("driving_cell", {})
    oc = pdk_conf.get("operating_conditions", {})

    search_dirs = [pdk_path(pdk_root, p) for p in pdk.get("search_dirs", [])]
    synthetic_libs = libs.get("synthetic", [])
    target_libs = [pdk_path(pdk_root, p) for p in get_obj(libs, "target")]
    link_libs = [pdk_path(pdk_root, p) for p in libs.get("link", target_libs)]
    symbol_libs = [pdk_path(pdk_root, p) for p in libs.get("symbol", [])]

    if not target_libs:
        fail("libraries.target must not be empty")

    cell_ref = driving.get("cell", "")
    cell_conf = {}
    if cell_ref:
        cells = pdk_conf.get("cells", {})
        cell_conf = get_obj(cells, cell_ref)
    driving_cell_name = driving.get("name", cell_conf.get("name", ""))
    driving_cell_pin = driving.get("pin", cell_conf.get("pin", "Y"))

    print(f"# Generated from {conf_path}. Do not edit.")
    print(f"# PDK config: {pdk_conf_path}")
    emit("asic_conf_name", get_obj(conf, "name"))
    emit("asic_process_name", get_obj(pdk_conf, "name"))
    emit("top_module", get_obj(conf, "top_module"))
    emit("clock_name", clock.get("name", "clk"))
    emit("clock_port", clock.get("port", clock.get("name", "clk")))
    emit("clock_period", get_obj(clock, "period"))
    emit("clock_uncertainty", clock.get("uncertainty", 0.25))
    emit("clock_latency", clock.get("latency", 0.60))
    emit("pdk_dir", pdk_root)
    emit_list("pdk_search_path", search_dirs)
    emit_list("synthetic_library_list", synthetic_libs)
    emit_list("target_library_list", target_libs)
    emit_list("link_library_list", ["*"] + link_libs + synthetic_libs)
    emit_list("symbol_library_list", symbol_libs)
    emit_list("rtl_defines", conf.get("rtl", {}).get("defines", ["SYNTHESIS"]))
    emit("rtl_list_file", os.path.abspath(args.rtl_file) if args.rtl_file else "")

    emit("input_delay_max_ratio", constraints.get("input_delay_max_ratio", 0.30))
    emit("input_delay_min_ratio", constraints.get("input_delay_min_ratio", 0.10))
    emit("output_delay_max_ratio", constraints.get("output_delay_max_ratio", 0.30))
    emit("output_delay_min_ratio", constraints.get("output_delay_min_ratio", 0.10))
    emit("max_transition", constraints.get("max_transition", 0.40))
    emit("max_fanout", constraints.get("max_fanout", 32))
    emit("output_load", constraints.get("output_load", 0.10))
    emit("critical_range_ratio", constraints.get("critical_range_ratio", 0.10))
    emit("high_fanout_net_threshold", constraints.get("high_fanout_net_threshold", 32))

    emit("driving_cell", driving_cell_name)
    emit("driving_cell_pin", driving_cell_pin)
    emit("driving_cell_input_transition_rise",
         driving.get("input_transition_rise", constraints.get("max_transition", 0.40)))
    emit("driving_cell_input_transition_fall",
         driving.get("input_transition_fall", constraints.get("max_transition", 0.40)))

    max_oc = oc.get("max", {})
    min_oc = oc.get("min", {})
    use_oc = bool(max_oc and min_oc)
    emit("use_operating_conditions", 1 if use_oc else 0)
    emit("operating_conditions_analysis_type", oc.get("analysis_type", "on_chip_variation"))
    emit("operating_conditions_max", max_oc.get("condition", ""))
    emit("operating_conditions_max_lib", max_oc.get("library", ""))
    emit("operating_conditions_min", min_oc.get("condition", ""))
    emit("operating_conditions_min_lib", min_oc.get("library", ""))


if __name__ == "__main__":
    main()
