#!/usr/bin/env python3

import json
import pathlib
import re
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
ITF_GEN_JSON = ROOT / "build/generated/itf.json"


def c_ident(name):
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    ident = re.sub(r"_+", "_", ident)
    return ident.strip("_")


def validate_events(type_name, events):
    if not isinstance(events, list):
        raise ValueError(f"pcm type {type_name} events must be list")
    for event in events:
        if not isinstance(event, str):
            raise ValueError(f"pcm type {type_name} event must be string")


def type_exists(desc, type_name):
    return type_name in desc["types"]


def get_type_def(desc, type_name):
    if type_name not in desc["types"]:
        raise ValueError(f"unknown pcm type: {type_name}")

    type_def = desc["types"][type_name]
    if not isinstance(type_def, dict):
        raise ValueError(f"pcm type {type_name} must be object")
    events = type_def.get("events", [])
    children = type_def.get("children", {})
    validate_events(type_name, events)
    if not isinstance(children, dict):
        raise ValueError(f"pcm type {type_name}.children must be object")
    for child_name, child_type in children.items():
        if not isinstance(child_type, str):
            raise ValueError(
                f"pcm type {type_name} child {child_name} must be type string")
        if not type_exists(desc, child_type):
            raise ValueError(
                f"pcm type {type_name} child {child_name} has unknown type "
                f"{child_type}")
    return events, children


def walk_type(desc, type_name, path, counters, instances, stack):
    if type_name in stack:
        cycle = " -> ".join(stack + [type_name])
        raise ValueError(f"pcm hierarchy type cycle: {cycle}")

    events, children = get_type_def(desc, type_name)

    hier = ".".join(path)
    if len(events) != 0:
        port = f"perf_{c_ident(hier)}_slv"
        instances.append({
            "hier": hier,
            "type": type_name,
            "port": port,
        })
    for event in events:
        idx = len(counters)
        name = f"{hier}.{event}"
        counters.append({
            "idx": idx,
            "hier": hier,
            "type": type_name,
            "port": f"perf_{c_ident(hier)}_slv",
            "event": event,
            "name": name,
            "enum": c_ident(name).upper(),
        })

    for child_name, child_type in children.items():
        walk_type(desc, child_type, path + [child_name],
            counters, instances, stack + [type_name])


def validate_desc(desc):
    types = desc.get("types")
    top = desc.get("top")
    if not isinstance(types, dict):
        raise ValueError("pcm types must be object")
    if not isinstance(top, dict):
        raise ValueError("pcm top must be object")

    for type_name in types:
        get_type_def(desc, type_name)

    top_name = top.get("name")
    top_type = top.get("type")
    if not isinstance(top_name, str):
        raise ValueError("pcm top.name must be string")
    if not isinstance(top_type, str):
        raise ValueError("pcm top.type must be string")
    if not type_exists(desc, top_type):
        raise ValueError(f"pcm top type {top_type} is unknown")


def load_desc(path):
    with open(path, "r", encoding="utf-8") as fp:
        desc = json.load(fp)

    validate_desc(desc)
    counters = []
    instances = []
    walk_type(desc, desc["top"]["type"], [desc["top"]["name"]],
        counters, instances, [])

    seen_enums = set()
    seen_names = set()
    seen_ports = set()
    for counter in counters:
        if counter["enum"] in seen_enums:
            raise ValueError(f"duplicate pcm enum: {counter['enum']}")
        if counter["name"] in seen_names:
            raise ValueError(f"duplicate pcm name: {counter['name']}")
        seen_enums.add(counter["enum"])
        seen_names.add(counter["name"])
    for instance in instances:
        if instance["port"] in seen_ports:
            raise ValueError(f"duplicate pcm rtl port: {instance['port']}")
        seen_ports.add(instance["port"])

    desc["counters"] = counters
    desc["instances"] = instances
    desc["counter_num"] = len(counters)
    return desc


def write_if_changed(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != text:
        path.write_text(text, encoding="utf-8")


def gen_software_maps(desc):
    counter_num = desc["counter_num"]
    lines = [
        "#ifndef PCM_MAP_H",
        "#define PCM_MAP_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "/* Generated by tools/pcmgen.py from desc/pcm.json. */",
        f"#define PCM_COUNTER_NUM {counter_num}u",
        "#define PCM_REG_CLEAR   (PCM_COUNTER_NUM * 8u)",
        "",
        "enum {",
    ]
    for counter in desc["counters"]:
        lines.append(f"    PCM_CNT_{counter['enum']} = {counter['idx']},")
    lines.extend([
        "};",
        "",
        "#define PCM_COUNTER_DESC_NUM \\",
        f"    {len(desc['counters'])}u",
        "",
        "static inline const char *pcm_counter_name(uint32_t idx)",
        "{",
        "    static const char * const names[] = {",
    ])
    for counter in desc["counters"]:
        lines.append(f"        \"{counter['name']}\",")
    lines.extend([
        "    };",
        "",
        "    if (idx >= PCM_COUNTER_DESC_NUM)",
        "        return NULL;",
        "    return names[idx];",
        "}",
        "",
        "#endif",
        "",
    ])
    text = "\n".join(lines)
    write_if_changed(ROOT / "sdk/drivers/pcm/pcm_map.h", text)
    write_if_changed(ROOT / "cases/user/pcm_dump/pcm_map.h", text)


def gen_rtl_perf(desc):
    counter_num = desc["counter_num"]
    svh_lines = [
        "`ifndef PCM_PERF_SVH",
        "`define PCM_PERF_SVH",
        "",
        "/* Generated by tools/pcmgen.py from desc/pcm.json. */",
        f"`define RVB_PCM_COUNTER_NUM {counter_num}",
        "",
        "`endif",
        "",
    ]
    lines = [
        "// Generated by tools/pcmgen.py from desc/pcm.json.",
        "",
        "`include \"dbg/pcm_perf.svh\"",
        "",
        f"module pcm_perf #(",
        "    parameter int COUNTER_NUM = `RVB_PCM_COUNTER_NUM",
        ")(",
        "    output logic [COUNTER_NUM-1:0] inc_en,",
    ]
    for idx, instance in enumerate(desc["instances"]):
        comma = "," if idx < len(desc["instances"]) - 1 else ""
        lines.append(
            f"    perf_{instance['type']}_if_t.slv {instance['port']}{comma}")
    lines.extend([
        ");",
        "    always_comb begin",
        "        inc_en = '0;",
    ])
    for counter in desc["counters"]:
        lines.append(
            f"        inc_en[{counter['idx']}] = "
            f"{counter['port']}.pkt.{counter['event']};"
            f" // {counter['name']}")
    lines.extend([
        "    end",
        "endmodule",
        "",
    ])
    write_if_changed(ROOT / "base/rtl/dbg/pcm_perf.svh",
        "\n".join(svh_lines))
    write_if_changed(ROOT / "base/rtl/dbg/pcm_perf.sv",
        "\n".join(lines))


def gen_model_map(desc):
    counter_num = desc["counter_num"]
    lines = [
        "#ifndef DBG_PCM_MAP_H",
        "#define DBG_PCM_MAP_H",
        "",
        "#include \"base/types.h\"",
        "",
        "/* Generated by tools/pcmgen.py from desc/pcm.json. */",
        f"#define DBG_PCM_COUNTER_NUM {counter_num}u",
        "#define DBG_PCM_REG_CLEAR   (DBG_PCM_COUNTER_NUM * 8u)",
        "",
        "typedef struct dbg_pcm_map_entry {",
        "    u32 idx;",
        "    const char *hier;",
        "    const char *event;",
        "    const char *name;",
        "} dbg_pcm_map_entry_t;",
        "",
        "static const dbg_pcm_map_entry_t g_dbg_pcm_map[] = {",
    ]
    for counter in desc["counters"]:
        lines.append(
            f"    {{ {counter['idx']}u, \"{counter['hier']}\", "
            f"\"{counter['event']}\", \"{counter['name']}\" }},")
    lines.extend([
        "};",
        "",
        "#endif",
        "",
    ])
    write_if_changed(ROOT / "base/model/dbg/pcm_map.h", "\n".join(lines))


def gen_itf_json(desc):
    base_path = ROOT / "desc/itf.json"
    with open(base_path, "r", encoding="utf-8") as fp:
        itf_desc = json.load(fp)

    itfs = itf_desc["itfs_desc"]
    for type_name in desc["types"]:
        events, _ = get_type_def(desc, type_name)
        if len(events) == 0:
            continue
        itfs[f"perf_{type_name}"] = {
            "type": "none",
            "rtl_only": True,
            "payloads": [
                { "name": event, "width": 1 } for event in events
            ]
        }

    write_if_changed(ITF_GEN_JSON, json.dumps(itf_desc, indent=4) + "\n")


def gen_itfs():
    subprocess.run([
        sys.executable,
        str(ROOT / "tools/itfgen.py"),
        str(ITF_GEN_JSON),
    ], cwd=ROOT, check=True)


def main(argv):
    desc_path = pathlib.Path(argv[1]) if len(argv) > 1 else ROOT / "desc/pcm.json"
    if not desc_path.is_absolute():
        desc_path = ROOT / desc_path
    desc = load_desc(desc_path)
    gen_software_maps(desc)
    gen_rtl_perf(desc)
    gen_model_map(desc)
    gen_itf_json(desc)
    gen_itfs()


if __name__ == "__main__":
    main(sys.argv)
